CREATE TABLE usuarios (
ID_Usuario INT PRIMARY KEY,
Nombre VARCHAR2(50) NOT NULL,
Apellido VARCHAR2(50) NOT NULL,
Documento_Identidad VARCHAR2(20) NOT NULL UNIQUE,
Correo_Electronico VARCHAR2(100) NOT NULL UNIQUE,
Telefono VARCHAR2(20) NOT NULL,
Fecha_Ingreso DATE NOT NULL,
Fecha_Salida DATE,
Salario DECIMAL(10,2) NOT NULL
);
