name: CI

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install assertpy pytest coverage psycopg2-binary Flask
          # Si tu proyecto es instalable, puedes usar:
          # python -m pip install -e .

      - name: Run tests with coverage
        env:
          PYTHONPATH: src
        run: |
          coverage run --source=src -m pytest -q
          coverage xml

  sonarqube:
    name: SonarQube Cloud
    runs-on: windows-latest
    # Ejecutar sólo en push a main (equivalente a la configuración original)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage assertpy psycopg2-binary Flask
          # Si tu proyecto es instalable, puedes usar:
          # python -m pip install -e .

      - name: Run tests and collect coverage
        env:
          PYTHONPATH: src
        run: |
          coverage run --source=src -m pytest -q
          coverage xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
